### ISSUE TITLE
How to make custom 'tiny' builds of MAME4Wii for just a specific driver?

### ISSUE THREAD

**Issue by saulfabregwiivc** [nebiun/MAME4Wii#4]
Hi there @nebiun. It's me, saulfabreg.

Glad to see some more progress in arcade emulation for Wii, so first of all thanks for bring us yet another port of MAME for the Wii.
**I can see that the "cores" that MAME4Wii uses are now split for save lots of RAM, so it's now so neat and also runs many games without problems.** (Thanks again for splitting into different cores.)

Now i have a question.
I was wondering, if you could help me about how to make my own custom "split core" (tiny builds) of MAME4Wii for just a specific driver, like you do for your cores (ex. **MAME4Wii__GAME__NAMCO__KONAMI__**).
One driver i wanted to try is for the games which use the **"Konami Mystic Warriors"** (**mystwarr.c**) driver, which is a game many Wii users wanted to play in years but no arcade emulator other than the outdated SDL MAME by Nuvalo can run it, and i'm having a hard time trying to use it.

Seeing your build instructions i see i have to run the command **./build_all.sh** for compile, but it's a pain to recompile everything for just test compiling a tiny build of MAME4Wii which have a specific driver...

is there any way for tell the compiler that i just want to recompile a specific tiny build, let's say the **__NAMCO__KONAMI__** one?

Thanks again for this arcade emulator. :)

**Comment by nebiun** [comment]
Well, it is simple.
You must edit file _src/mame/4wii.c_ here:
`#ifdef __SINGLE__`
`    DRIVER( spacefev )`
`//	DRIVER( tps )`
`#endif`

Replace the "rom" name (_spacefev_ in the upper code) with the name of rom you want play.
In some cases, you must add the bios rom, too.
How you know if a bios is needed and which?
Use grep. Example for overtop, that needs neogeo.
`grep -rw _ overtop_ src | grep "GAME("`
This is my output:
`src/mame/drivers/neodrvr.c:GAME( 1996, overtop,  neogeo,   neogeo,   neogeo,   neogeo,   ROT0, "ADK",              "Over Top", 0 )`
Overtop requires **neogeo**.

Then you can run
'single.sh'
to build MAME4Wii_Single.dol.

Hope this help.

Remember: big roms do not work, neither as single game.

**Comment by saulfabregwiivc** [comment]
thank you, i got to compile a few builds and they all work, except the ones for games which MAME4Wii consider "big roms".
I really had hopes for play Mystic Warriors but unfortunately i got kicked to HBC after loading...
Even after uncommented the mystwarr.c code before rebuilding, it's the same error. Dang.

If you can accept a suggestion, **is make MAME4Wii load all the rom files into Wii's MEM2 (64 MB) instead of MEM1 (24 MB), or even better, a sort of code for use the NAND as virtual memory (VM) for allow loading larger roms.**
Or even better, **make some MAME routines to put temporal files and loaded roms into MEM2 or a VM, so they won't overload MEM1**.
(More further info about MEM1 and MEM2: https://wiibrew.org/wiki/Memory_map )

Btw, here's the log i got for my mystwarr build:
```
MAME4Wii v.  (May 30 2024)
Name:             Description:
mystwarr          "Mystic Warriors (ver EAA)"

1717078762.038625:MAME4Wii v.  (May 30 2024)
1717078762.076283:main: Enter main loop (argc=1)
1717078762.080725:cli_execute: argv[0] = sd:/apps/mame4wii_mystwarr/boot.dol
1717078762.090390:wii_init_audio: start 0x806904c0
1717078762.091606:wii_init_audio: end 0x806904c0
1717078762.127859:osd_set_mastervolume: Start 0
1717078762.129382:osd_set_mastervolume: Start -32
1717078762.130932:osd_set_mastervolume: Start -32
1717078763.700439:osd_set_mastervolume: Start -32
1717078763.701978:wii_video_cleanup: start
1717078763.703464:wii_audio_cleanup: thread ON machine 0x806904c0
1717078763.720439:wii_init_audio: start 0x806904c0
1717078763.721908:wii_init_audio: end 0x806904c0
1717078764.836497:osd_set_mastervolume: Start 0
1717078765.044510:_wii_malloc failed: size 8388608 [src/emu/drawgfx.c:175]
1717078765.045982:src/emu/restrack.c(84):Failed to allocate 8388608 bytes (src/emu/drawgfx.c:175)
1717078765.047432:mame_execute: return from setjmp: 3
1717078765.049041:wii_video_cleanup: start
1717078765.050511:wii_audio_cleanup: thread ON machine 0x806904c0
1717078765.054410:main: cli_execute <none> rtn 3
1717078765.055862:wii_shutdown_input: start
1717078765.057369:wii_shutdown_input: input thread turned off
1717078765.058830:wii_shutdown_input: end
1717078765.060280:wii_shutdown_audio: start
1717078765.061731:wii_audio_thread: Audio thread finished
1717078765.063186:wii_shutdown_audio: audio thread turned off
1717078765.064653:wii_shutdown_audio: end
1717078765.066104:wii_shutdown_video: start
1717078765.067556:wii_shutdown_video: video thread turned off
1717078765.094188:wii_shutdown_video: end

```

Anyways, thanks for responding.

**Comment by nebiun** [comment]
MAME4Wii is a PORTING of original mame 0.135 sources compiled using devKitPro.
I cut many drivers and code to shrink the executables, but I cannot do miracles.
 src/emu/drawgfx.c is a mame source and try to alloc 8 Mb and fail. BUT this is NOT the first malloc!!!
RAM is needed for audio and video Wii drivers and a *lot* for mame emulator engine. You can enable debug in _wii_malloc to trace all the mallocs and verify the amount of ram required for game that you want play.
About MEM1 and MEM2: libogc already use both:
[https://github.com/devkitPro/libogc/blob/master/libogc/sbrk.c](url)

NAND is Flash Memory, not RAM, and write on Wii NAND is not safe. So, if you want try, do it by yourself on your hardware.
